---
- name: Install dnf
  ansible.builtin.dnf:
    name: firewalld
    state: present

- name: Open SSH port
  ansible.posix.firewalld:
    port: "{{ ansible_port }}/tcp"
    permanent: true
    state: enabled

- name: Start firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true  
...
