---
- name: Enabling Duo Unix in SELinux
  ansible.posix.seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  loop:
    - "pam_duo_permit_sshd"
    - "pam_duo_permit_local_login"

- name: Finding pam_duo.so
  set_fact: 
    pam_duo_path: "{{lookup('first_found', pam_duo, errors='ignore')}}"
  vars:
    pam_duo:
      - "/lib/security/pam_duo.so"
      - "/lib64/security/pam_duo.so"

- name: Updating PAM configurations (sshd - 1)
  ansible.builtin.lineinfile:
    path: "{{ pam_sshd }}"
    regexp: '^#?auth\s+substack\s+password-auth'
    line: "#auth  substack password-auth"

- name: Updating PAM configurations (sshd - 2)
  ansible.builtin.lineinfile:
    path: "{{ pam_sshd }}"
    insertafter: '^#?auth\s+substack\s+password-auth'
    regexp: '^auth\s+required\s+pam_env'
    line: "auth  required pam_env.so"

- name: Updating PAM configurations (sshd - 3)
  ansible.builtin.lineinfile:
    path: "{{ pam_sshd }}"
    insertafter: '^auth\s+required\s+pam_env'
    regexp: '^auth\s+sufficient\s+{{ pam_duo_path }}'
    line: "auth  sufficient {{ pam_duo_path }}"

- name: Updating PAM configurations (sshd - 4)
  ansible.builtin.lineinfile:
    path: "{{ pam_sshd }}"
    insertafter: '^auth\s+sufficient\s+{{ pam_duo_path }}'
    regexp: '^auth\s+required\s+pam_deny'
    line: "auth  required pam_deny.so"

- name: Updating PAM configurations (system-auth - 1)
  ansible.builtin.lineinfile:
    path: "{{ pam_system_auth }}"
    regexp: '^#?\s?auth\s+sufficient\s+pam_unix.so\s+nullok'
    line: "# auth  sufficient pam_unix.so nullok try_first_pass"

- name: Updating PAM configurations (system-auth - 2)
  ansible.builtin.lineinfile:
    path: "{{ pam_system_auth }}"
    insertafter: '^#?\s+auth\s+sufficient\s+pam_unix.so\s+nullok\s+try_first_pass'
    regexp: '^auth\s+requisite\s+pam_unix.so\s+nullok\s+try_first_pass'
    line: "auth        requisite                                    pam_unix.so nullok try_first_pass"

- name: Updating PAM configurations (system-auth - 3)
  ansible.builtin.lineinfile:
    path: "{{ pam_system_auth }}"
    insertafter: '^auth\s+requisite\s+pam_unix.so\s+nullok\s+try_first_pass'
    regexp: '^auth\s+sufficient\s+{{ pam_duo_path }}'
    line: "auth        sufficient                                   {{ pam_duo_path }}"
...
