---
- name: Updating PAM configurations (Ubuntu)
  include_tasks:
    file: "{{ ansible_distribution | lower }}.yaml"
  when: ansible_distribution == 'Ubuntu' or
        ansible_distribution == 'CentOS' or
        ansible_distribution == 'Debian'

- name: Setting sudo timeout 
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: '^Defaults\s+env_reset'
    line: 'Defaults        env_reset,timestamp_timeout={{ sudo_timeout }}'
    validate: /usr/sbin/visudo -cf %s
...
