---
- name: Installing Duo GPG key (CentOS)
  ansible.builtin.rpm_key:
    state: present
    key: https://duo.com/DUO-GPG-PUBLIC-KEY.asc
    fingerprint: 08C2 A645 DDF2 40B8 5844 068D 7A45 0864 C1A0 7A85 

- name: Copying Duo repository file (CentOS)
  ansible.builtin.copy:
    src: duosecurity.repo
    dest: /etc/yum.repos.d/duosecurity.repo
    owner: root
    group: root

- name: Installing Duo Unix (CentOS)
  dnf:
    name: duo_unix
    state: latest
    update_cache: yes
...
