---
- name: Installing Duo GPG key (CentOS)
  ansible.builtin.rpm_key:
    state: present
    key: "{{ duo_key_url }}"
    fingerprint: "{{ duo_key_id }}"

- name: Copying Duo repository file (CentOS)
  ansible.builtin.copy:
    src: duosecurity.repo
    dest: /etc/yum.repos.d/duosecurity.repo
    owner: root
    group: root

- name: Installing Duo Unix (CentOS)
  dnf:
    name: duo_unix
    state: latest
    update_cache: yes
...
