---
- name: Update SSH port depending on execution tags
  set_fact:
    ansible_port: 22
  when: "'full' is not in ansible_run_tags"

- name: Gather facts if necessary
  setup:
  when: "'full' is not in ansible_run_tags"

- name: Install Duo Unix package
  include_tasks:
    file: "{{ ansible_distribution | lower }}.yaml"
  when: ansible_distribution == 'Ubuntu' or
        ansible_distribution == 'CentOS' or
        ansible_distribution == 'Debian'

- name: Configure Duo Unix package  
  template:
    src: pam_duo.conf.j2
    dest: /etc/duo/pam_duo.conf
    owner: root
    group: root
    mode: 0600
...
