---
- name: Installing Duo GPG key (Ubuntu)
  ansible.builtin.apt_key:
    url: "{{ duo_key_url }}"
    state: present
    id: "{{ duo_key_id }}"

- name: Adding repository for Duo Unix (Ubuntu)
  ansible.builtin.apt_repository:
    repo: "deb https://pkg.duosecurity.com/Ubuntu {{ ansible_distribution_release }} main"
    state: present
    filename: duosecurity.list

- name: Installing Duo Unix (Ubunut)
  ansible.builtin.apt:
    name: duo-unix
    state: present
    update_cache: yes
...
